# Generated by Django 4.2.9 on 2024-01-17 19:19

from django.db import migrations, models
import tables.validators


class Migration(migrations.Migration):

    dependencies = [
        ("tables", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(
                blank=True,
                max_length=17,
                validators=[tables.validators.validate_telephone_number],
            ),
        ),
    ]
